"""
routers/milestone_escrow_router.py — New escrow state machine API
=================================================================
All business logic delegates to services.milestone_state_machine and
services.milestone_service. These routes are intentionally dumb.

Financial endpoints (/fund, /approve, /admin/resolve) require an
Idempotency-Key header (UUID generated by the frontend). The backend
checks for duplicate keys before processing to prevent double-charging
on network retries.

Routes:
  POST /milestones/{id}/fund            — client funds a milestone
  POST /milestones/{id}/submit          — freelancer submits work
  POST /milestones/{id}/approve         — client approves work
  POST /milestones/{id}/reject          — client rejects with feedback
  POST /milestones/{id}/escalate        — either party escalates to dispute
  POST /milestones/{id}/admin/resolve   — admin arbitration
  POST /contracts/{id}/auto-split       — create milestones from project budget
  GET  /milestones/{id}/escrow          — get full milestone detail
"""

import uuid as _uuid
from datetime import datetime, timezone, timedelta

from fastapi import APIRouter, Depends, Header, HTTPException
from sqlalchemy.orm import Session, joinedload

import models
import schema
from auth import get_current_user, require_admin
from db import get_db
from services.milestone_service import split_milestones
from services.milestone_state_machine import state_machine, NEW_STYLE_STATUSES

router = APIRouter(tags=["Milestone Escrow"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _get_milestone_or_404(milestone_id: int, db: Session) -> models.Milestone:
    m = db.query(models.Milestone).filter(
        models.Milestone.milestone_id == milestone_id
    ).first()
    if not m:
        raise HTTPException(404, "Milestone not found.")
    return m


def _check_idempotency(key: str, db: Session) -> bool:
    """Returns True if this key was already processed (duplicate request)."""
    return db.query(models.IdempotencyLog).filter(
        models.IdempotencyLog.key == key
    ).first() is not None


def _assert_new_style(milestone: models.Milestone) -> None:
    if milestone.status not in NEW_STYLE_STATUSES:
        raise HTTPException(
            400,
            "This milestone uses the legacy status flow. "
            "Use PUT /milestones/{id}/status instead.",
        )


def _assert_not_terminal(milestone: models.Milestone) -> None:
    _TERMINAL = {
        models.MilestoneStatus.closed_success,
        models.MilestoneStatus.closed_refunded,
        models.MilestoneStatus.closed_auto_approve,
        models.MilestoneStatus.closed_auto_refund,
    }
    if milestone.status in _TERMINAL:
        raise HTTPException(400, f"Milestone is already closed ({milestone.status.value}).")


# ── GET /milestones/{id}/escrow ───────────────────────────────────────────────

@router.get(
    "/milestones/{milestone_id}/escrow",
    response_model=schema.MilestoneDetailResponse,
    summary="Get full escrow milestone detail",
)
def get_milestone_detail(
    milestone_id: int,
    me:           models.User = Depends(get_current_user),
    db:           Session     = Depends(get_db),
):
    milestone = (
        db.query(models.Milestone)
        .options(
            joinedload(models.Milestone.contract)
            .joinedload(models.Contract.project)
            .joinedload(models.Project.client),
            joinedload(models.Milestone.contract)
            .joinedload(models.Contract.freelancer),
        )
        .filter(models.Milestone.milestone_id == milestone_id)
        .first()
    )
    if not milestone:
        raise HTTPException(404, "Milestone not found.")
    return milestone


# ── POST /milestones/{id}/fund ────────────────────────────────────────────────

@router.post(
    "/milestones/{milestone_id}/fund",
    response_model=schema.MilestoneDetailResponse,
    summary="Fund a milestone (client)",
)
def fund_milestone(
    milestone_id:    int,
    body:            schema.MilestoneFundRequest,
    me:              models.User = Depends(get_current_user),
    db:              Session     = Depends(get_db),
    idempotency_key: str        = Header(..., description="Unique UUID — prevents double-charging on retry"),
):
    if _check_idempotency(idempotency_key, db):
        m = _get_milestone_or_404(milestone_id, db)
        return m

    _get_milestone_or_404(milestone_id, db)   # existence check before lock

    return state_machine.transition(
        milestone_id=milestone_id,
        new_status=models.MilestoneStatus.funded,
        actor=me,
        db=db,
        idempotency_key=idempotency_key,
    )


# ── POST /milestones/{id}/submit ──────────────────────────────────────────────

@router.post(
    "/milestones/{milestone_id}/submit",
    response_model=schema.MilestoneDetailResponse,
    summary="Submit work on a milestone (freelancer)",
)
def submit_milestone(
    milestone_id: int,
    body:         schema.MilestoneSubmitRequest,
    me:           models.User = Depends(get_current_user),
    db:           Session     = Depends(get_db),
):
    milestone = _get_milestone_or_404(milestone_id, db)

    # Freelancers can submit from funded OR in_revision (resubmit)
    if milestone.status == models.MilestoneStatus.in_revision:
        # Resubmit: go back to in_review via in_revision → in_review
        return state_machine.transition(
            milestone_id=milestone_id,
            new_status=models.MilestoneStatus.in_review,
            actor=me,
            db=db,
        )

    return state_machine.transition(
        milestone_id=milestone_id,
        new_status=models.MilestoneStatus.in_review,
        actor=me,
        db=db,
    )


# ── POST /milestones/{id}/approve ─────────────────────────────────────────────

@router.post(
    "/milestones/{milestone_id}/approve",
    response_model=schema.MilestoneDetailResponse,
    summary="Approve milestone work and release funds (client)",
)
def approve_milestone(
    milestone_id:    int,
    me:              models.User = Depends(get_current_user),
    db:              Session     = Depends(get_db),
    idempotency_key: str        = Header(..., description="Unique UUID — prevents duplicate fund release"),
):
    if _check_idempotency(idempotency_key, db):
        return _get_milestone_or_404(milestone_id, db)

    return state_machine.transition(
        milestone_id=milestone_id,
        new_status=models.MilestoneStatus.closed_success,
        actor=me,
        db=db,
        idempotency_key=idempotency_key,
    )


# ── POST /milestones/{id}/reject ──────────────────────────────────────────────

@router.post(
    "/milestones/{milestone_id}/reject",
    response_model=schema.MilestoneDetailResponse,
    summary="Request revision on submitted work (client)",
    description="Max 2 revisions. A 3rd rejection will be blocked — use /escalate instead.",
)
def reject_milestone(
    milestone_id: int,
    body:         schema.MilestoneRejectRequest,
    me:           models.User = Depends(get_current_user),
    db:           Session     = Depends(get_db),
):
    return state_machine.transition(
        milestone_id=milestone_id,
        new_status=models.MilestoneStatus.in_revision,
        actor=me,
        db=db,
        feedback=body.feedback,
    )


# ── POST /milestones/{id}/escalate ────────────────────────────────────────────

@router.post(
    "/milestones/{milestone_id}/escalate",
    response_model=schema.MilestoneDetailResponse,
    summary="Escalate to dispute (either party)",
)
def escalate_milestone(
    milestone_id: int,
    me:           models.User = Depends(get_current_user),
    db:           Session     = Depends(get_db),
):
    return state_machine.transition(
        milestone_id=milestone_id,
        new_status=models.MilestoneStatus.in_dispute,
        actor=me,
        db=db,
    )


# ── POST /milestones/{id}/admin/resolve ───────────────────────────────────────

@router.post(
    "/milestones/{milestone_id}/admin/resolve",
    response_model=schema.MilestoneDetailResponse,
    summary="Admin dispute arbitration (admin only)",
    description="resolution: force_pay | force_refund | split (requires split_percentage 1–99)",
)
def admin_resolve_milestone(
    milestone_id:    int,
    body:            schema.AdminResolveRequest,
    me:              models.User = Depends(require_admin),
    db:              Session     = Depends(get_db),
    idempotency_key: str        = Header(..., description="Unique UUID — prevents duplicate arbitration"),
):
    if _check_idempotency(idempotency_key, db):
        return _get_milestone_or_404(milestone_id, db)

    return state_machine.resolve_arbitration(
        milestone_id=milestone_id,
        resolution_type=body.resolution,
        split_percentage=body.split_percentage,
        actor=me,
        db=db,
        note=body.note,
        idempotency_key=idempotency_key,
    )


# ── POST /contracts/{id}/auto-split ───────────────────────────────────────────

@router.post(
    "/contracts/{contract_id}/auto-split",
    response_model=schema.MilestoneAutoSplitResponse,
    status_code=201,
    summary="Auto-split contract budget into milestones (client)",
    description="Creates new milestones in AWAITING_FUNDS status. Contract must be active with no existing new-style milestones.",
)
def auto_split_milestones(
    contract_id: int,
    me:          models.User = Depends(get_current_user),
    db:          Session     = Depends(get_db),
):
    contract = (
        db.query(models.Contract)
        .options(
            joinedload(models.Contract.project),
            joinedload(models.Contract.milestones),
        )
        .filter(models.Contract.contract_id == contract_id)
        .first()
    )
    if not contract:
        raise HTTPException(404, "Contract not found.")

    if contract.status != models.ContractStatus.active:
        raise HTTPException(400, f"Contract is not active (status: {contract.status.value}).")

    # Access check
    if me.role != models.UserRole.admin:
        client = db.query(models.Client).filter(models.Client.user_id == me.id).first()
        if not client or contract.project.client_id != client.client_id:
            raise HTTPException(403, "Only the client or admin can auto-split milestones.")

    # Guard: no existing new-style milestones
    existing_new = [m for m in contract.milestones if m.status in NEW_STYLE_STATUSES]
    if existing_new:
        raise HTTPException(
            400,
            "Contract already has new-style escrow milestones. Cannot auto-split again.",
        )

    budget = contract.project.budget
    if not budget or budget <= 0:
        raise HTTPException(400, "Project budget must be set before auto-splitting.")

    splits = split_milestones(budget)

    # Space milestones 2 weeks apart
    now = datetime.now(timezone.utc)
    created = []
    for i, s in enumerate(splits):
        deadline = now + timedelta(weeks=(i + 1) * 2)
        m = models.Milestone(
            contract_id=contract_id,
            title=s["title"],
            description=None,
            amount=s["amount"],
            status=models.MilestoneStatus.awaiting_funds,
            due_date=deadline,
            deadline=deadline,
        )
        db.add(m)
        created.append(s)

    db.commit()

    return schema.MilestoneAutoSplitResponse(
        milestones=created,
        total_amount=budget,
        count=len(created),
    )
